import random
#questions=["How are you?","How old are you?","What's your name?"]
#while True:
#    answ=input(random.choice(questions)+':')
#    if answ=='stop':
#        break
#s='hello'
#lst=[letter.upper() for letter in s if letter > 'f']
#print(lst)

#rnd_int=[random.randint(1,100) for i in range(10)]
#print(rnd_int)
#rnd_int=[number for number in rnd_int if number > 25]
#print(rnd_int)
#d={i:random.randint(-100,100)**3 for i in range(1,11,3)}
#print(d)

a,b=[0,6]
a=a or b-3
print(a)